apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-bar
spec:
  template:
    spec:
      containers:
      - name: najena
        env:
        - name: MESSAGE
          value: "Bar Canary Frontend 2 Response"
        - name: BACKEND_SERVICE
          value: "backend-bar"
