apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-foo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: najena
        env:
        - name: MESSAGE
          value: "Foo Canary Frontend"
