apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-foo
spec:
  template:
    spec:
      containers:
      - name: najena
        env:
        - name: MESSAGE
          value: "Foo Canary Frontend 2 Response"
        - name: BACKEND_SERVICE
          value: "backend-foo"
