apiVersion: apply.k8s.io/v1beta1
kind: ContinuousApply
metadata:
  name: canary
spec:
  repo:
    owner: pwittrock
    repo: najena
  user: firionavie-canary
  targets:
  - path: config/canary/backend
  - path: config/canary/frontend
  match:
    labels:
    - "rollout"
    assignee: "firionavie-canary"
  beforeActions:
    addLabels:
    - "rollout-started-canary"
  afterActions:
    # mark rollout as done
    removeLabels:
    - "rollout-started-canary"
    addLabels:
    - "rollout-done-canary"
    # unassign self, we are done
    removeAssignees:
    - "firionavie-canary"
    # assign to rollout to uswest and useast
    addAssignees:
    - "firionavie-uswest"
    - "firionavie-useast"
  components:
    gitCredentials:
     key: "firionavie-canary"
     secret:
       name: "applier-github-credentials"
    serviceAccount: "firionavie"
