apiVersion: apply.k8s.io/v1beta1
kind: ContinuousApply
metadata:
  name: useast
spec:
  repo:
    owner: pwittrock
    repo: najena
  user: firionavie-useast
  targets:
  - path: config
  - path: config2
  match:
    labels:
    - "rollout"
    assignee: "firionavie-useast"
  beforActions:
    addLabels:
    - "rollout-started-useast"
  afterActions:
    removeLabels:
    - "rollout-started-useast"
    removeAssignees:
    - "firionavie-useast"
    addLabels:
    - "rollout-done-useast"
  components:
    gitCredentials:
     key: "firionavie-useast"
     secret:
       name: "applier-github-credentials"
    serviceAccount: "firionavie"
