apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: frontend-foo
  name: frontend-foo
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: frontend-foo
  template:
    metadata:
      labels:
        app: frontend-foo
    spec:
      containers:
      - image: pwittrock/gs-spring-boot-docker
        name: najena
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: BACKEND_SERVICE
          value: "backend-foo"
        - name: VERSION
          value: "3"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-foo
  name: frontend-foo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-foo
  type: LoadBalancer
