apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: frontend-bar
  name: frontend-bar
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: frontend-bar
  template:
    metadata:
      labels:
        app: frontend-bar
    spec:
      containers:
      - image: pwittrock/gs-spring-boot-docker
        name: najena
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: BACKEND_SERVICE
          value: "backend-bar"
        - name: VERSION
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-bar
  name: frontend-bar
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-bar
  type: LoadBalancer
