apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld2
  name: helloworld2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld2
  template:
    metadata:
      labels:
        app: helloworld2
    spec:
      containers:
      - image: pwittrock/najena:springboot
        name: najena
        env:
        - name: MESSAGE
          value: "Hello from app 2"
