apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld1
  name: helloworld1
spec:
  replicas: 6
  minReadySeconds: 10
  selector:
    matchLabels:
      app: helloworld1
  template:
    metadata:
      labels:
        app: helloworld1
    spec:
      containers:
      - image: pwittrock/gs-spring-boot-docker
        name: najena
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: MESSAGE
          value: "Hello from app 1 - 4"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld1
  name: helloworld1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld1
  type: LoadBalancer
