apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld2
  name: helloworld2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld2
  template:
    metadata:
      labels:
        app: helloworld2
    spec:
      containers:
      - image: pwittrock/gs-spring-boot-docker
        name: najena
        env:
        - name: MESSAGE
          value: "Hello from app 2 - 3"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld2
  name: helloworld2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld2
  type: LoadBalancer
