apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend-foo
  name: backend-foo
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: backend-foo
  template:
    metadata:
      labels:
        app: backend-foo
    spec:
      containers:
      - image: pwittrock/gs-spring-boot-docker
        name: najena
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
          requests:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: MESSAGE
          value: "Foo Backend 1 Response"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-foo
  name: backend-foo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-foo
