apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-bar
spec:
  template:
    spec:
      containers:
      - name: najena
        env:
        - name: MESSAGE
          value: "Bar USWEST Backend 1 Response"
